### ISSUE TITLE
KV Namespace needs to be created

### ISSUE THREAD

**Issue by adam0white** [jarylc/cf-workers-chatgpt-discord-bot#1]
Hey @jarylc, I gave this a try and it looks good, thank you!
I might be creating a pull request regarding this issue, and a few other things on my mind. For now, here's the issue.
The `kv_namespaces` in `wrangler.toml` needs to be set up.
https://github.com/jarylc/cf-workers-chatgpt-discord-bot/blob/66d1205c25bdeb9c1b8bda5ea60cc66292010d9a/wrangler.toml#LL7C62-L7C62
I ran ```npx wrangler kv:namespace create CHATGPT_DISCORD_BOT_KV``` in order to create a new namespace and pasted that ID in my `wrangler.toml`. This should be a step in 'Getting Started'.

**Comment by jarylc** [comment]
Ah, I should've added a step to remove those lines if you don't want to create a KV and have context.

**Comment by jarylc** [comment]
Made README.md slightly clearer
