### ISSUE TITLE
Give the ability to set a system message

### ISSUE THREAD

**Issue by adam0white** [jarylc/cf-workers-chatgpt-discord-bot#2]
Sending a [system message](https://platform.openai.com/docs/guides/chat/introduction) is an easy way of customizing the chatbot. With the help of it, a developer can customize the behavior of the endpoint. Example: `You're a class mentor chatbot developed by @jarylc. Only respond to math questions.`, etc.

**Comment by jarylc** [comment]
Yeah, I will do that when I have free time, probably add an environment variable for this.

**Comment by jarylc** [comment]
Added `CHATGPT_BEHAVIOR` environment variable in `wrangler.toml` to add this
