### ISSUE TITLE
Send end-user ID to OpenAI

### ISSUE THREAD

**Issue by adam0white** [jarylc/cf-workers-chatgpt-discord-bot#3]
Sending end-user IDs to OpenAI is [suggested by them](https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids) to detect abuse, and is a good practice.

**Comment by jarylc** [comment]
Sounds like a good idea, I'll implement this when I can

**Comment by jarylc** [comment]
A SHA-1 hash (to add some privacy) of the user's ID prepended with `dc_` will be sent to the API with the latest change
